### ISSUE TITLE
Packet structure

### ISSUE THREAD

**Issue by FlorianCassayre** [firebolt55439/Diep.io-Protocol#11]
Hello there,

I've been working on trying to desobfuscate that protocol and I found your repository. I was only working with wireshark since the actual obfuscated js file is really bad. I figured out some facts that you didn't find, and reciprocally.
For example, the packet type isn't defined by its length but by its header. The header is a 1-byte long ID that defines how the packet should be read.
You can have a look at my work here : https://github.com/FlorianCassayre/diep.io-protocol
If we merge our researches, we'll almost have the full protocol.

**Comment by hxxr** [comment]
We've found the headers out for packets sent by the server, but that sounds interesting. Also, a client-to-server packet starting with `0x04` is an upgrade to a tank, for example, sniper or twin.

**Comment by firebolt55439** [comment]
Welcome to the team 😄
