### ISSUE TITLE
connecting server

### ISSUE THREAD

**Issue by xiaoas** [firebolt55439/Diep.io-Protocol#14]
entering sth such as "http://diep.io/#B82A2BB5BB3099" will automatically direct you to a server, can you explain?How to use it?

**Comment by firebolt55439** [comment]
It is similar to the agar.io "party" feature - it lets you connect to a friend's server and play with them on their team. Take a look at [this](https://www.reddit.com/r/Diepio/comments/4oy2xp/interesting_party_hex_code_patterns/) and [this](https://www.reddit.com/r/Diepio/comments/4pxp2a/diepio_party_code_breakdown_kinda/) for more information on the composition of these server links.
