### ISSUE TITLE
Party code algorithm

### ISSUE THREAD

**Issue by ghost** [firebolt55439/Diep.io-Protocol#16]
[/u/mrgoober_](https://www.reddit.com/user/mrgoober_) reverse-engineered how the party code works in [this thread](https://www.reddit.com/r/Diepio/comments/4pxp2a/diepio_party_code_breakdown_kinda/), and I think it deserves a place in the wiki. What do you think about it? This might also be useful for other encoded hex strings.

**Comment by hxxr** [comment]
Hmm...So the digits have been swapped. That's interesting. This might have also been used for packets. Thanks for the info!

**Comment by firebolt55439** [comment]
This repo primarily deals with Websocket-related protocol, but this seems
interesting enough to warrant an exception. Should
have a basic Wiki page done soon.
