### ISSUE TITLE
Only receiving one packet when upgrading

### ISSUE THREAD

**Issue by hxxr** [firebolt55439/Diep.io-Protocol#2]
Something's wrong, because whenever I upgrade, I only see one packet of length two. Also, upgrading Health Regen gives me [3, 14], but Max Health gives me [3, 12].

**Comment by firebolt55439** [comment]
That's strange - I'm going to run through it on my computer and see if I can reproduce the error.

**Comment by firebolt55439** [comment]
You're right, it appears to be only one packet. The codes also appear to follow the pattern [3, 14] for Health Regen, [3, 12] for Max Health, [3, 10] for Body Damage, etc.

I'll update the wiki to reflect these changes. Thanks for pointing this out!
