### ISSUE TITLE
Missing Tanks...?

### ISSUE THREAD

**Issue by hxxr** [firebolt55439/Diep.io-Protocol#21]
As you know, I have been updating tank values, While I was doing that, I realized something odd. Every tank value seems to be an even number. When a new tank is added, then its value will be two more than that of the previously added tank. That means that every even number should be taken, up to (currently) `82`. The problem is, that is not true. There are "holes" in the tank value dictionary. It is very unlikely that this is a mistake. The missing tank values are `32`, `54`, and possibly `0`. Maybe these are the special tanks, such as the Mothership. I doubt playing as the Mothership will help, because I have, and found nothing.

I have checked twice for if I missed any tanks.

**Comment by firebolt55439** [comment]
I suspect the missing three tanks could be Mothership, Dominator, and Arena Closer.

**Comment by hxxr** [comment]
@firebolt55439 It seems that they have finally changed the protocol, now every tank has a different value.

**Comment by kNowo** [comment]
@hxxr and the stats too, So far these are the new values that I have gotten: 

**Stats:**

```
 4: 'Health Regen',
 6: 'Max Health',
 0: 'Body Damage',
 2: 'Bullet Speed',
12: 'Bullet Penetration',
14: 'Bullet Damage',
 8: 'Reload',
10: 'Movement Speed'
```

**Tanks:**

```
 44: 'Twin',
 34: 'Sniper',
 32: 'Machine Gun',
 62: 'Flank Guard',
102: 'Smasher',
 60: 'Tri-Angle',
  0: 'Booster',
 30: 'Fighter',
 38: 'Quad Tank',
 36: 'Octo Tank',
126: 'Auto 5',
124: 'Auto 3',
 96: 'Auto Gunner',
 52: 'Twin Flank',
 10: 'Triple Twin',
 40: 'Triple Shot',
 42: 'Triplet',
 50: 'Penta Shot',
 20: 'Sprayer',
  6: 'Gunner',
110: 'Gunner Trapper',
 58: 'Destroyer',
 28: 'Hybrid',
 98: 'Landmine'

```

I'll be finishing Flank Guard branchafter this, so you might want to get the other branches so we could finish this asap

EDIT: Flank Guard branch is done, now going for Twin
EDIT 2: All branch except sniper is done. I'm not sure if I want to keep going seeing as how sniper branch is very big and will likely take a long time. Until next time, see ya!

**Comment by hxxr** [comment]
@kNowo You can just send a pull request instead of telling me

**Comment by hxxr** [comment]
@kNowo It seems that they are re-shuffling for every update...

**Comment by kNowo** [comment]
@hxxr yeah, I was afraid of that. Is there anything we can do about this? Maybe try to get the new values somewhere else? See if the game is doing any request to any files for the latest randomized values?

**Comment by hxxr** [comment]
@kNowo That seems very likely. We could try to either get them from other packets (again), or we can try to get them from the `d.js` script (very low chance of success). Either way, the most likely reason that this could be happening is because they are aware of our existance. But they can't hide it forever.

**Comment by terjanq** [comment]
Oh, I'm pretty sure they can :) You have no idea how much troubles I got
because of my diep.io extension, same thing with agar.io extensions...

**Comment by kNowo** [comment]
@hxxr @terjanq Well, I'll leave this matter to you guys. I'm very new at these kind of things and javascript itself. Hope you two can come up with something in the near future. Let me know if you need an extra hand to help with something.

**Comment by terjanq** [comment]
I quit diep.io long ago, the game is not popular anymore and for me, it became really boring.
