### ISSUE TITLE
This Doesnt Work

### ISSUE THREAD

**Issue by SharkFinPro** [firebolt55439/Diep.io-Protocol#22]
Diep.io stops extension users from playing

**Comment by hxxr** [comment]
@SharkFinPro Thank you for notifying us, I will see what I can do about this, if there is anything to do.

**Comment by terjanq** [comment]
Just look at my extension: https://github.com/terjanq/xDiep.io

The whole project was created to bypass these detections and as I see It's still working.

**Comment by terjanq** [comment]
I think `WebSocket.prototype.send.toString()` needs to be overwritten as I did it.

**Comment by hxxr** [comment]
@terjanq Is this the same mod from diephack.tk? Because I heard that was patched.

**Comment by terjanq** [comment]
Yes it is but now it's open source. Just try it... it works fine.

**Comment by hxxr** [comment]
I'll try it, but I'm not sure if I will be able to find the piece of code that you are talking about, since I didn't even know how our script worked when I first joined.

**Comment by terjanq** [comment]
Nvm, I've just made a pull request with quick fix.
