### ISSUE TITLE
Diep.io Party Codes

### ISSUE THREAD

**Issue by eli-rich** [firebolt55439/Diep.io-Protocol#24]
Hello, I think this project will be excellent and could add a ton of functionality to the game. Do you guys know anything about how party codes work? So far we only have [this](https://www.reddit.com/r/Diepio/comments/509665/diepio_party_code_observations/). The developer has made it much harder to switch teams by manipulating the codes.

**Comment by hxxr** [comment]
Nope.

Well other than that, no.

**Comment by hxxr** [comment]
Also, they seem to be doing this to everything. This script can no longer detect specific tank upgrades.

**Comment by eli-rich** [comment]
@hxxr Do you think this project will be completed? I'm sure eventually someone will outsmart the dev.

**Comment by hxxr** [comment]
If someone is going to outsmart the dev, it's probably not going to be me.

**Comment by terjanq** [comment]
Zeach is very stubborn, he doesn't want anyone to tinker with his games and he tries his best to   prevent it. You can try your best too but then he can change something and all your work becomes useless. So this won't be ever completed, same as agar.io protocol after asm.js translate which is too hard to work with.
