### ISSUE TITLE
Do we have access to the game's code itself?

### ISSUE THREAD

**Issue by epicbob57** [firebolt55439/Diep.io-Protocol#25]
For example, what says: "Motherships have 7K health" or "Machine gun's base reload is higher".

This would be interesting to know.

**Comment by hxxr** [comment]
Yes, you can find the files `c.js` and `d.js` on their page. But what you want is most likely stored on the server.

**Comment by epicbob57** [comment]
Specifically what I'm trying to find is a player's "true" stats, I.E. the actual amount of damage a bullet would do or the actual amount of hitpoints one has.

**Comment by hxxr** [comment]
Yes, that would be stored on the server.

**Comment by hxxr** [comment]
Everything that happens to you, for example, being killed or killing someone, is all calculated on the server. When you fire a bullet, your computer tells the server that you are firing a bullet in this direction, and the server calculates the exact position of the bullet every 40 milliseconds and sends the position back to your computer.

The amount of damage you do is calculated based off of your stats, which @firebolt55439 has observed being sent by the client, and the stats are then tweaked based off of which tank you are, which I have observed also being sent by the client.

**Comment by epicbob57** [comment]
So, no luck for me :,(
