### ISSUE TITLE
Packet Dumping

### ISSUE THREAD

**Issue by nullobsi** [firebolt55439/Diep.io-Protocol#28]
in the script on the diep.io website there is something that tells you to uncomment to dump packets. if this isn't being used could this be used to provide further analysis of the communications between client/server?
![screenshot_20160919150707](https://cloud.githubusercontent.com/assets/22283693/18650600/c10cd30a-7e7a-11e6-8a4e-f66f8634805a.png)

**Comment by firebolt55439** [comment]
It could be used for that, but the problem is that the game client itself shuts down when detecting an unauthorized handler (e.g. extension).

**Comment by nullobsi** [comment]
maybe instead of an extension you could dump the log and a program could collect it? it would probably not be worth the extra effort but we should probably find a way to use it by first blocking the "blocked" message

**Comment by firebolt55439** [comment]
The only issue with that approach is that to populate the log with entries in the first place, the extension has to be running. Diep.io game code alone offers no native facilities to log packets, which is why we need the extension in the first place.
