### ISSUE TITLE
Packet 8 - Server to Client

### ISSUE THREAD

**Issue by ghost** [firebolt55439/Diep.io-Protocol#41]
I don't know if it's a new implemented packet but it's so weird.
Structure:
Uint8Array [8, uint8byte, zero terminated utf8 string (probably a hash, ends always with "_1")]
Example: [8, 4, 51, 48, 48, 100, 100, 100, 54, 102, 49, 102, 98, 51, 100, 54, 57, 100, 95, 49, 0, 56, 50, 50, 49, 49, 56, 48, 101, 99, 54, 100, 53, 51, 50, 51, 50, 95, 49, 0, 57, 57, 53, 51, 52, 50, 51, 101, 56, 56, 52, 52, 50, 50, 98, 54, 95, 49, 0, 100, 51, 101, 52, 56, 50, 57, 53, 56, 51, 51, 54, 50, 98, 52, 56, 95, 49, 0]
String Result: " 300ddd6f1fb3d69d_1 8221180ec6d53232_1 9953423e884422b6_1 d3e4829583362b48_1 "
Was it already implemented or it's new?

**Comment by firebolt55439** [comment]
It does not appear to be detected in `chrome_ext/modifier.js` after a cursory review. I would recommend taking a look at the aforementioned file to see what packet types are currently detected and how if you're interested in further deciphering the protocol.

**Comment by ghost** [comment]
the chrome extension is too broken xd it just logs packet 2
also packet 8 is received only when u hit an object (havent tested with a player)

**Comment by cx88** [comment]
Looks like this have to do with achievements. If you open the console, all of the id's for local storage ends with `_1`, and the values here match with the content of my local storage data:

    A::300ddd6f1fb3d69d_1 20
    A::8221180ec6d53232_1 20
    A::9953423e884422b6_1 15
    A::d3e4829583362b48_1 15

I'd suspect the packet you got was due to the "It hurts when I do this" achievement.

**Comment by ghost** [comment]
Yeah the packet 8 is for the achievements. Thanks!!
