### ISSUE TITLE
Serverbound 01 - Not up to date

### ISSUE THREAD

**Issue by cx88** [firebolt55439/Diep.io-Protocol#42]
According to https://github.com/firebolt55439/Diep.io-Protocol/wiki/Protocol, the serverbound 01 packet should contain the info about tank movement and firing in the last byte.  
However, looks like in the current version, this information have been moved to be the byte 1 & 2.

    00000001 - header / byte 0
    100DSAWL - byte 1
    0001000R - byte 2
    
    L/R = left/right mouse
    WASD = movement direction
 
I was unable to decrypt the bytes that followed the first 3 bytes, but it looks like they're the data of the coordinate of the mouse, relative to the center of the map.

Can someone correct the information on the wiki, or help me with decrypting the coordinate of the mouse?

**Comment by firebolt55439** [comment]
I have not had time to keep the wiki up-to-date, but if you would like, I can give you permissions to update the wiki as a collaborator.
